server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
management:
  endpoints:
    web:
      exposure:
        include: health
eureka:
  client:
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetchRegistry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    # Industry standard: Fetch registry every 30 seconds
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    # Industry standard: Send heartbeat every 30 seconds
    lease-renewal-interval-in-seconds: 30
    # Industry standard: Expire instance after 90 seconds without heartbeat
    lease-expiration-duration-in-seconds: 90
  server:
    # Keep self-preservation disabled to prevent emergency mode
    enable-self-preservation: false
    # Industry standard: Run eviction task every 60 seconds
    eviction-interval-timer-in-ms: 60000
    # Industry standard: 85% renewal threshold
    renewal-percent-threshold: 0.85
    # Industry standard: Update response cache every 30 seconds
    response-cache-update-interval-ms: 30000
    # Industry standard: Cache expires after 10 minutes
    response-cache-auto-expiration-in-seconds: 600
